# Generated by Django 5.1.5 on 2025-11-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=500)),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(blank=True, max_length=500)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('spotify_url', models.URLField()),
                ('genres', models.JSONField(blank=True, default=list)),
                ('popularity', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_e124dd_idx'), models.Index(fields=['track_id'], name='recommendat_track_i_42a8aa_idx')],
            },
        ),
    ]
